version: '3.8'

services:
  # 서비스 이름 정의
  unified-search-api:
    # Dockerfile이 있는 경로를 기준으로 이미지를 빌드합니다.
    # context: . 는 현재 디렉토리를 의미합니다.
    build:
      context: .
      dockerfile: Dockerfile
    
    # 포트 매핑 설정
    # 호스트의 8833번 포트를 컨테이너의 8000번 포트와 연결합니다.
    # 형식: "HOST:CONTAINER"
    ports:
      - "8833:8000"
      
    # 볼륨 매핑 설정
    # 호스트의 현재 디렉토리(.)를 컨테이너의 /app 디렉토리와 동기화합니다.
    # 이를 통해 호스트에서 코드를 수정하면 별도의 빌드 없이 컨테이너에 즉시 반영됩니다.
    # 형식: "HOST_PATH:CONTAINER_PATH"
    volumes:
      - .:/app
      
    # 재시작 정책 설정
    # 컨테이너가 어떤 이유로든 중지될 경우, 항상 자동으로 다시 시작하도록 설정합니다.
    restart: always
    
    # .env 파일 참조
    # 호스트의 .env 파일을 컨테이너 내부에서 환경 변수로 사용할 수 있도록 설정합니다.
    # 이를 통해 컨테이너가 API 키 등의 민감한 정보에 접근할 수 있습니다.
    env_file:
      - .env
